### ISSUE TITLE
LocalFuzzyHistogramHyperbolization: Ready for release

### ISSUE THREAD

**Issue by jconejero** [PixInsight/PJSR#52]
Hi Frank,

LocalFuzzyHistogramHyperbolization is now ready for release IMO. See the latest commits I have made with small modifications to your code. Since the script had no license information, I have taken the liberty to add [PCL License 1.0](https://github.com/PixInsight/PCL/blob/master/LICENSE.txt) headers. Should you prefer a different open-source license, please feel free to replace it.

Please let me know if you agree with this version for immediate release as an official update for all platforms, including your documentation. I plan on sending a massive email notification to all users.

**Comment by fweidenbusch** [comment]
Hi Juan,

I agree with this version. Thanks.

**Comment by jconejero** [comment]
Hi Frank,

We are on the air now :) The updates have been released and the massive email has been sent. I am sure this is going to be a big success. Thank you so much for this nice contribution and please keep more coming!
